import express from "express";
import dotenv from "dotenv";
import { connectDb } from "./Db/connectionDb.js";
import { routerApp } from "./src/app_router.js";
dotenv.config();
const app = express();
const port = process.env.PORT;
connectDb();
routerApp(app, express);
app.listen(port, () => console.log(`Example app listening on port ${port}!`));
